### ISSUE TITLE
Runtime error on GitHub Actions

### ISSUE THREAD

**Issue by macie** [macie/unittest.sh#11]
**What happened?**
Tests running on GitHub Actions CI returns error:
```
tput: No value for $TERM and no -T specified
./unittest: 221: [: Illegal number: 
```

**How to reproduce?**
Add file `.github/workflows/unittests.yml` with:
```yaml
name: Unit tests
on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Unit tests with unittest.sh
      run: make test
```

**Additional info**
unittest version: 23.3
